### ISSUE TITLE
i am stupid. and every town i tryu to create town, it says "

### ISSUE THREAD

**Issue by Thyrus1** [Atherys/AtherysTowns#152] opened 2021-01-30 05:19 UTC
**Description:** _What's wrong?_

**Reproduction Steps:** _How do we re-create it?_

**Expected Behavior:** _What should be happening?_

**Observed Behavior:** _What is happening instead?_

**Comment by AaronFoley** [comment] 2021-01-30 09:34
@Thyrus1 please add more details to this issue.

**Comment by AaronFoley** [comment] 2021-01-30 09:35
Duplicate of #153

**Closed** 2021-01-30 09:35 UTC
Labels: duplicate
